# Generated by Django 2.1.4 on 2019-02-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zakaz', 'verbose_name_plural': 'Zakaz'},
        ),
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Tovar v korzine', 'verbose_name_plural': 'Tovary v korzine'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Tovar v Zakaze', 'verbose_name_plural': 'Tovary v Zakaze'},
        ),
    ]
