# Generated by Django 2.1.4 on 2019-02-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190207_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Zakaza', 'verbose_name_plural': 'Statusy Zakaza'},
        ),
    ]
