# Generated by Django 2.1.4 on 2019-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190113_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular_models',
            field=models.BooleanField(default=True),
        ),
    ]
