# Generated by Django 2.1.4 on 2019-01-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_popular_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_popular_models',
        ),
    ]
