# Generated by Django 2.1.4 on 2019-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190118_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='productimage',
            name='new_models',
            field=models.BooleanField(default=False),
        ),
    ]
