# Generated by Django 2.1.4 on 2019-01-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190118_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_models',
            field=models.BooleanField(default=False),
        ),
    ]
