# Generated by Django 2.1.4 on 2019-01-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='new_models',
        ),
    ]
