# Generated by Django 2.1.4 on 2019-02-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productimage_new_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tovar', 'verbose_name_plural': 'Tovary'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategoriya Tovara', 'verbose_name_plural': 'Kategoriya Tovarov'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Photografia', 'verbose_name_plural': 'Photografii'},
        ),
    ]
